version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=test/pytest-results
artifacts:
  files:
    - '**/*'
reports:
  pytest_reports:
    files:
      - pytest-results
    base-directory: test/
    file-format: JUNITXML