name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Se deben deshabilitar los clones superficiales para un análisis más relevante
          
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: pruebas+coverage
        id: pruebas
        run: | 
          python -m coverage run -m unittest discover tests 
          python -m coverage xml -i 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener información de PR, si la hay
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.sources=. -Dsonar.exclusions=**/node_modules/**,**/dist/**  # Exclusiones personalizadas si es necesario
          SONAR_OTHER_PROPS: "sonar.inclusions=** -x **/*.c, **/*.cpp, **/*.h, **/*.m, **/*.mm"